version: '3'
services:
  app:
    build: . # build the image from the Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/MiniTwit.Web/Data:/app/Data  #mount our existing Data folder to /app/Data (need to match connection string) in container (docker volume)

#Inspiration/guide: https://medium.com/@Shamimw/docker-a-complete-tutorial-part3-docker-compose-2e3b2f568a6f
